server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/v1/usuarios/**

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/v1/hoteles/**

        - id: calificacion-service
          uri: lb://calificacion-service
          predicates:
            - Path=/api/v1/calificaciones/**

eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/